local_auth_mode: true

app_root: testapp

postgres_config:
  username: user
  host: psg
  password: pwd
  database_name: postgres
  database_ssl_mode: disable
  port: 5432

google_auth:
  client_id: xxx

