name: Go Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20' # Use the version of Go your project requires

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod tidy

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest # Use the latest version of golangci-lint
        args: --issues-exit-code=0 # Optional: set exit code to 0 to prevent pipeline failure on warnings

    - name: Run golangci-lint
      run: golangci-lint run ./...

    - name: Test
      run: make test
